apiVersion: v1
kind: Service
metadata:
  name: {{ template "glauth.fullname" . }}
  labels:
    name: {{ template "glauth.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ template "glauth.fullname" . }}
  ports:
{{- range $port := .Values.service.ports }}
  - name: {{ $port.name }}
    port: {{ $port.external }}
    targetPort: {{ $port.internal }}
{{- if $port.node }}
    nodePort: {{ $port.node }}
{{- end}}
    protocol: TCP
{{- end}}