apiVersion: v1
kind: ConfigMap
metadata:
  name: glauth-config
data:
{{- if .Values.backend.file }}
  config.cfg: |-
{{ .Files.Get .Values.backend.file | indent 4 }}
{{- else if eq .Values.backend.type "config" }}
  config.cfg: |-
{{ .Files.Get "config/sample-simple.cfg" | indent 4 }}
{{- else if eq .Values.backend.type "database" }}
  {{- if eq .Values.database.engine "postgres" }}
  config.cfg: |-
{{ tpl (.Files.Get "config/sample-postgres.cfg") . | indent 4 }}
  {{- else }}
  config.cfg: |-
{{ .Files.Get "config/sample-sqlite.cfg" | indent 4 }}
  {{- end }}
{{- end}}