apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "glauth.fullname" . }}
  labels:
    app: {{ template "glauth.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "glauth.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ template "glauth.fullname" . }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
{{- range $port := .Values.service.ports }}
        - containerPort: {{ $port.internal }}
{{- end}}
        command: ["/app/glauth", "-c", "/app/config/config.cfg"]
        {{- if and (eq .Values.config.backend.type "database") (eq .Values.config.database.engine "postgres") .Values.config.database.postgres.createResources }}
        envFrom:
        - secretRef:
            name: {{ .Values.database.postgres.existingSecretName | default (printf "%s-%s" (.Values.database.postgres.secretName | default "postgres-user") (include "glauth.fullname" .)) }}
        {{- end }}
        livenessProbe:
          exec:
            command:
            - sh
            - "-c"
            - "echo OK"
          initialDelaySeconds: 5
          periodSeconds: 5
        volumeMounts:
{{- if .Values.config.storage }}
        - name: {{ .Chart.Name }}-data
          mountPath: /app/config
{{- end}}
        - name: {{ .Chart.Name }}-config
          mountPath: /app/config/config.cfg
          subPath: config.cfg
        readinessProbe:
          exec:
            command:
            - sh
            - "-c"
            - "echo OK"
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
{{- if .Values.config.storage }}
      - name: {{ .Chart.Name }}-data
        persistentVolumeClaim:
          claimName: {{ .Chart.Name }}-data
{{- end}}
      - name: {{ .Chart.Name }}-config
        configMap:
          name: glauth-config