{{- if and .Values.config.storage (ne .Values.config.backend.type "config") }}
{{- if not .Values.config.storage.existingClaim | default false }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Chart.Name }}-data
spec:
  accessModes:
{{- if not .Values.config.storage.accessMode }}
{{- if and (eq .Values.config.backend.type "database") (eq .Values.config.database.engine "postgres") }}
    - ReadWriteOnce
{{- else }}
    - ReadWriteMany
{{- end }}
{{- else }}
    - "{{ .Values.config.storage.accessMode }}"
{{- end }}
{{- if .Values.config.storage.className }}
  storageClassName: "{{ .Values.config.storage.className }}"
{{- end }}
{{- if not .Values.config.storage.mode }}
  volumeMode: Filesystem
{{- else }}
  volumeMode: "{{ .Values.config.storage.mode }}"
{{- end }}
  resources:
    requests:
      storage: {{ .Values.config.storage.size }}
{{- end }}
{{- end }}