{{- if eq .Values.config.backend.type "database" }}
{{- if eq .Values.config.database.engine "sqlite" }}
{{- if .Values.config.database.sqlite.shell | default true }}
apiVersion: v1 
kind: Pod 
metadata: 
  name: glauth-sqlite-client
spec: 
  containers: 
  - name: glauth-sqlite-client
    image: nouchka/sqlite3
    stdin: true 
    tty: true 
    volumeMounts:
    - name: {{ .Chart.Name }}-data
      mountPath: /root/db
  volumes:
  - name: {{ .Chart.Name }}-data
    persistentVolumeClaim:
      claimName: {{ .Chart.Name }}-data
{{- end}}
{{- end}}
{{- end}}